graph TD
   style B stroke:#333,stroke-width:4px
   style H1 stroke:#333,stroke-width:4px
   style H7 stroke:#333,stroke-width:4px
   style H10 stroke:#333,stroke-width:4px
   A --> H1["H1 = H(A)"]
   B --> H2["H2 = H(B) (target)"]
   C --> H3["H3 = H(C)"]
   D --> H4["H4 = H(D)"]
   E --> H5["H5 = H(E)"]
   H1 --> H6["H6 = H(H1 +H2)"]
   H2 --> H6
   H3 --> H7["H7 = H(H3 + H4)"]
   H4 --> H7
   H5 --> H8["H8 = H(H5+H5)"]
   H6 --> H9["H9 = H(H6+H7)"]
   H7 --> H9
   H8  --> H10["H10 = H(H8+H8)"]
   H9  --> R["HRoot = H(H9+H10)"]
   H10 --> R
